name = "durable-object-websocket"
main = "src/index.ts"
compatibility_date = "2024-12-12"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]